export declare const sapService: {
    createOrUpdateVanInventorySAP(payload: any, userId?: number): Promise<{
        finalInventory: {
            id: number | undefined;
            source_system_label: string | null;
            user_id: number | undefined;
            last_updated: Date | null | undefined;
            is_active: string | undefined;
            createdate: Date | null | undefined;
            createdby: number | undefined;
            updatedate: Date | null | undefined;
            updatedby: number | null | undefined;
            log_inst: number | null | undefined;
            location_id: number | null | undefined;
            location_type: string | null | undefined;
            vehicle_id: number | null | undefined;
            vehicle_code: string | null | undefined;
            sales_person_code: string | null | undefined;
            loading_type: string | undefined;
            status: string | undefined;
            document_date: Date | null | undefined;
            sale_type: string | null | undefined;
            van_inventory_users: {
                name: string;
                id: number;
                email: string;
                employee_id: string;
                sap_code: string | null;
            } | undefined;
            vehicle: {
                model: string | null;
                id: number;
                sap_code: string | null;
                type: string;
                vehicle_number: string;
                make: string | null;
            } | null | undefined;
            van_inventory_depot: {
                name: string;
                id: number;
                sap_code: string | null;
                code: string;
                city: string | null;
            } | null | undefined;
            van_inventory_items_inventory: ({
                van_inventory_items_products: {
                    product_product_batches: ({
                        batch_lot_product_batches: {
                            id: number;
                            is_active: string;
                            createdate: Date | null;
                            createdby: number;
                            updatedate: Date | null;
                            updatedby: number | null;
                            log_inst: number | null;
                            expiry_date: Date;
                            base_quantity: number | null;
                            batch_number: string;
                            lot_number: string | null;
                            manufacturing_date: Date;
                            quantity: number;
                            remaining_quantity: number;
                            supplier_name: string | null;
                            purchase_price: import("@prisma/client-runtime-utils").Decimal | null;
                            quality_grade: string | null;
                            storage_location: string | null;
                            productsId: number | null;
                        };
                    } & {
                        id: number;
                        is_active: string;
                        createdate: Date | null;
                        createdby: number;
                        updatedate: Date | null;
                        updatedby: number | null;
                        log_inst: number | null;
                        product_id: number;
                        base_quantity: number | null;
                        quantity: number;
                        batch_lot_id: number;
                    })[];
                    product_tax_master: {
                        name: string;
                        id: number;
                        is_active: string;
                        createdate: Date | null;
                        createdby: number;
                        updatedate: Date | null;
                        updatedby: number | null;
                        log_inst: number | null;
                        code: string;
                        description: string | null;
                        tax_rate: import("@prisma/client-runtime-utils").Decimal;
                    } | null;
                    product_unit_of_measurement: {
                        symbol: string | null;
                        name: string;
                        id: number;
                        is_active: string;
                        createdate: Date | null;
                        createdby: number;
                        updatedate: Date | null;
                        updatedby: number | null;
                        log_inst: number | null;
                        category: string | null;
                        description: string | null;
                        conversion_rate: number | null;
                        sub_unit: string | null;
                    };
                    serial_numbers_products: ({
                        serial_numbers_customers: {
                            name: string;
                            id: number;
                            email: string | null;
                            phone_number: string | null;
                            address: string | null;
                            is_active: string;
                            createdate: Date | null;
                            createdby: number;
                            updatedate: Date | null;
                            updatedby: number | null;
                            log_inst: number | null;
                            depot_id: number | null;
                            code: string;
                            latitude: import("@prisma/client-runtime-utils").Decimal | null;
                            longitude: import("@prisma/client-runtime-utils").Decimal | null;
                            short_name: string | null;
                            zones_id: number | null;
                            customer_type_id: number | null;
                            customer_channel_id: number | null;
                            customer_category_id: number | null;
                            type: string | null;
                            gps_status: string | null;
                            internal_code_one: string | null;
                            internal_code_two: string | null;
                            contact_person: string | null;
                            city: string | null;
                            state: string | null;
                            zipcode: string | null;
                            credit_limit: import("@prisma/client-runtime-utils").Decimal | null;
                            outstanding_amount: import("@prisma/client-runtime-utils").Decimal | null;
                            route_id: number | null;
                            salesperson_id: number | null;
                            nfc_tag_code: string | null;
                            last_visit_date: Date | null;
                            outlet_images: string | null;
                            profile_picture: string | null;
                            city_id: number | null;
                            district_id: number | null;
                            region_id: number | null;
                        } | null;
                    } & {
                        id: number;
                        is_active: string;
                        createdate: Date | null;
                        createdby: number;
                        updatedate: Date | null;
                        updatedby: number | null;
                        log_inst: number | null;
                        status: string | null;
                        serial_number: string;
                        warranty_expiry: Date | null;
                        customer_id: number | null;
                        product_id: number;
                        location_id: number | null;
                        batch_id: number | null;
                        sold_date: Date | null;
                    })[];
                } & {
                    unit_of_measurement: number;
                    name: string;
                    id: number;
                    is_active: string;
                    createdate: Date | null;
                    createdby: number;
                    updatedate: Date | null;
                    updatedby: number | null;
                    log_inst: number | null;
                    sap_code: string | null;
                    code: string;
                    brand_id: number;
                    description: string | null;
                    route_type_id: number | null;
                    category_id: number;
                    subunit_id: number | null;
                    sub_category_id: number;
                    base_price: import("@prisma/client-runtime-utils").Decimal | null;
                    tax_rate: import("@prisma/client-runtime-utils").Decimal | null;
                    tax_id: number | null;
                    outlet_group_id: number | null;
                    tracking_type: string | null;
                    product_type_id: number | null;
                    product_target_group_id: number | null;
                    product_web_order_id: number | null;
                    volume_id: number | null;
                    flavour_id: number | null;
                    shelf_life_id: number | null;
                    vat_percentage: import("@prisma/client-runtime-utils").Decimal | null;
                    weight_in_grams: import("@prisma/client-runtime-utils").Decimal | null;
                    volume_in_liters: import("@prisma/client-runtime-utils").Decimal | null;
                };
                van_inventory_items_batch_lot: {
                    id: number;
                    expiry_date: Date;
                    batch_number: string;
                } | null;
            } & {
                id: number;
                parent_id: number;
                remarks: string | null;
                notes: string | null;
                discount_amount: import("@prisma/client-runtime-utils").Decimal | null;
                tax_amount: import("@prisma/client-runtime-utils").Decimal | null;
                total_amount: import("@prisma/client-runtime-utils").Decimal | null;
                product_id: number;
                serial_id: number | null;
                is_cancelled: string | null;
                base_quantity: number | null;
                product_name: string | null;
                quantity: number;
                batch_lot_id: number | null;
                sap_docnum: string | null;
                sap_docentry: string | null;
                source_system: string | null;
                sap_lineid: string | null;
                sap_item_code: string | null;
                unit: string | null;
                unit_price: import("@prisma/client-runtime-utils").Decimal;
            })[] | undefined;
            van_inventory_stock_movements: {
                id: number;
                remarks: string | null;
                movement_type: string;
                movement_date: Date | null;
                quantity: number;
            }[] | undefined;
        };
        wasUpdate: boolean;
    }>;
};
//# sourceMappingURL=sap.service.d.ts.map