const templateKeyMap = {
  requestRejected: 'request_rejected',
  requestAccepted: 'request_accepted',
  notifyApprover: 'notify_approver',
  notifyNextApprover: 'notify_next_approver',
  contractExpiryAlert: 'contract_expiry_alert',
  interviewRemark: 'interview_remark',
  interviewRemarkAccepted: 'interview_remark_accepted',
  interviewRemarkRejected: 'interview_remark_rejected',
  notifyNextRemarkApprover: 'notify_next_remark_approver',
  notificationSetupCreated: 'notification_setup_created',
  notificationSetupUpdated: 'notification_setup_updated',
  notificationSetupDeleted: 'notification_setup_deleted',
  systemNotificationSetupCreated: 'system_notification_created',
  systemNotificationSetupUpdated: 'system_notification_updated',
  systemNotificationSetupDeleted: 'system_notification_deleted',
  locationResetNotifyApprover: 'location_reset_notify_approver',
  locationResetApproved: 'location_reset_approved',
  locationResetRejected: 'location_reset_rejected',
  customerCreationNotifyApprover: 'customerCreationNotifyApprover',
  customerCreationApproved: 'customerCreationApproved',
  customerCreationRejected: 'customerCreationRejected',
};

export default templateKeyMap;
