export declare const resolvers: {
    Query: {
        assetMasters: (_: any, { filter, limit, offset }: any) => Promise<({
            asset_master_image: {
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                asset_id: number;
                image_url: string;
                caption: string | null;
                uploaded_by: string | null;
                uploaded_at: Date | null;
            }[];
            asset_maintenance_master: {
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                remarks: string | null;
                asset_id: number;
                maintenance_date: Date;
                issue_reported: string | null;
                action_taken: string | null;
                cost: import("@prisma/client-runtime-utils").Decimal | null;
                technician_id: number;
            }[];
            asset_master_asset_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                asset_type_id: number;
                description: string | null;
            } | null;
            asset_master_asset_types: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                category: string | null;
                description: string | null;
            };
        } & {
            brand: string | null;
            name: string;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            code: string;
            serial_number: string;
            warranty_expiry: Date | null;
            asset_type_id: number;
            assigned_to: string | null;
            barcode: string | null;
            nfc_tag: string | null;
            purchase_date: Date | null;
            current_location: string | null;
            current_status: string | null;
            asset_sub_type_id: number | null;
        })[]>;
        assetMaster: (_: any, { id }: {
            id: number;
        }) => Promise<({
            asset_master_image: {
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                asset_id: number;
                image_url: string;
                caption: string | null;
                uploaded_by: string | null;
                uploaded_at: Date | null;
            }[];
            asset_maintenance_master: {
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                remarks: string | null;
                asset_id: number;
                maintenance_date: Date;
                issue_reported: string | null;
                action_taken: string | null;
                cost: import("@prisma/client-runtime-utils").Decimal | null;
                technician_id: number;
            }[];
            asset_master_asset_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                asset_type_id: number;
                description: string | null;
            } | null;
            asset_master_asset_types: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                category: string | null;
                description: string | null;
            };
        } & {
            brand: string | null;
            name: string;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            code: string;
            serial_number: string;
            warranty_expiry: Date | null;
            asset_type_id: number;
            assigned_to: string | null;
            barcode: string | null;
            nfc_tag: string | null;
            purchase_date: Date | null;
            current_location: string | null;
            current_status: string | null;
            asset_sub_type_id: number | null;
        }) | null>;
        coolers: (_: any, { filter, limit, offset }: any) => Promise<({
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            } | null;
            cooler_inspections: {
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                action_taken: string | null;
                cooler_id: number;
                visit_id: number | null;
                inspected_by: number;
                inspection_date: Date | null;
                temperature: import("@prisma/client-runtime-utils").Decimal | null;
                is_working: string;
                issues: string | null;
                images: string | null;
                latitude: import("@prisma/client-runtime-utils").Decimal | null;
                longitude: import("@prisma/client-runtime-utils").Decimal | null;
                action_required: string;
                next_inspection_due: Date | null;
            }[];
            cooler_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                description: string | null;
            } | null;
            cooler_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                cooler_type_id: number;
                description: string | null;
            } | null;
            cooler_asset_master: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                serial_number: string;
                warranty_expiry: Date | null;
                asset_type_id: number;
                assigned_to: string | null;
                barcode: string | null;
                nfc_tag: string | null;
                purchase_date: Date | null;
                current_location: string | null;
                current_status: string | null;
                asset_sub_type_id: number | null;
            } | null;
            coolers_customers: {
                name: string;
                id: number;
                email: string | null;
                depot_id: number | null;
                phone_number: string | null;
                address: string | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                latitude: import("@prisma/client-runtime-utils").Decimal | null;
                longitude: import("@prisma/client-runtime-utils").Decimal | null;
                code: string;
                short_name: string | null;
                zones_id: number | null;
                customer_type_id: number | null;
                customer_channel_id: number | null;
                customer_category_id: number | null;
                type: string | null;
                gps_status: string | null;
                internal_code_one: string | null;
                internal_code_two: string | null;
                contact_person: string | null;
                city: string | null;
                state: string | null;
                zipcode: string | null;
                credit_limit: import("@prisma/client-runtime-utils").Decimal | null;
                outstanding_amount: import("@prisma/client-runtime-utils").Decimal | null;
                route_id: number | null;
                salesperson_id: number | null;
                nfc_tag_code: string | null;
                last_visit_date: Date | null;
                outlet_images: string | null;
                profile_picture: string | null;
            };
        } & {
            brand: string | null;
            model: string | null;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            status: string | null;
            technician_id: number | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            customer_id: number;
            code: string;
            asset_master_id: number | null;
            serial_number: string | null;
            capacity: number | null;
            install_date: Date | null;
            last_service_date: Date | null;
            next_service_due: Date | null;
            cooler_type_id: number | null;
            cooler_sub_type_id: number | null;
            energy_rating: string | null;
            warranty_expiry: Date | null;
            maintenance_contract: string | null;
            last_scanned_date: Date | null;
        })[]>;
        cooler: (_: any, { id }: {
            id: number;
        }) => Promise<({
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            } | null;
            cooler_inspections: {
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                action_taken: string | null;
                cooler_id: number;
                visit_id: number | null;
                inspected_by: number;
                inspection_date: Date | null;
                temperature: import("@prisma/client-runtime-utils").Decimal | null;
                is_working: string;
                issues: string | null;
                images: string | null;
                latitude: import("@prisma/client-runtime-utils").Decimal | null;
                longitude: import("@prisma/client-runtime-utils").Decimal | null;
                action_required: string;
                next_inspection_due: Date | null;
            }[];
            cooler_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                description: string | null;
            } | null;
            cooler_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                cooler_type_id: number;
                description: string | null;
            } | null;
            cooler_asset_master: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                serial_number: string;
                warranty_expiry: Date | null;
                asset_type_id: number;
                assigned_to: string | null;
                barcode: string | null;
                nfc_tag: string | null;
                purchase_date: Date | null;
                current_location: string | null;
                current_status: string | null;
                asset_sub_type_id: number | null;
            } | null;
            coolers_customers: {
                name: string;
                id: number;
                email: string | null;
                depot_id: number | null;
                phone_number: string | null;
                address: string | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                latitude: import("@prisma/client-runtime-utils").Decimal | null;
                longitude: import("@prisma/client-runtime-utils").Decimal | null;
                code: string;
                short_name: string | null;
                zones_id: number | null;
                customer_type_id: number | null;
                customer_channel_id: number | null;
                customer_category_id: number | null;
                type: string | null;
                gps_status: string | null;
                internal_code_one: string | null;
                internal_code_two: string | null;
                contact_person: string | null;
                city: string | null;
                state: string | null;
                zipcode: string | null;
                credit_limit: import("@prisma/client-runtime-utils").Decimal | null;
                outstanding_amount: import("@prisma/client-runtime-utils").Decimal | null;
                route_id: number | null;
                salesperson_id: number | null;
                nfc_tag_code: string | null;
                last_visit_date: Date | null;
                outlet_images: string | null;
                profile_picture: string | null;
            };
        } & {
            brand: string | null;
            model: string | null;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            status: string | null;
            technician_id: number | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            customer_id: number;
            code: string;
            asset_master_id: number | null;
            serial_number: string | null;
            capacity: number | null;
            install_date: Date | null;
            last_service_date: Date | null;
            next_service_due: Date | null;
            cooler_type_id: number | null;
            cooler_sub_type_id: number | null;
            energy_rating: string | null;
            warranty_expiry: Date | null;
            maintenance_contract: string | null;
            last_scanned_date: Date | null;
        }) | null>;
        coolersByCustomer: (_: any, { customerId }: {
            customerId: number;
        }) => Promise<({
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            } | null;
            cooler_inspections: {
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                action_taken: string | null;
                cooler_id: number;
                visit_id: number | null;
                inspected_by: number;
                inspection_date: Date | null;
                temperature: import("@prisma/client-runtime-utils").Decimal | null;
                is_working: string;
                issues: string | null;
                images: string | null;
                latitude: import("@prisma/client-runtime-utils").Decimal | null;
                longitude: import("@prisma/client-runtime-utils").Decimal | null;
                action_required: string;
                next_inspection_due: Date | null;
            }[];
            cooler_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                description: string | null;
            } | null;
            cooler_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                cooler_type_id: number;
                description: string | null;
            } | null;
            cooler_asset_master: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                serial_number: string;
                warranty_expiry: Date | null;
                asset_type_id: number;
                assigned_to: string | null;
                barcode: string | null;
                nfc_tag: string | null;
                purchase_date: Date | null;
                current_location: string | null;
                current_status: string | null;
                asset_sub_type_id: number | null;
            } | null;
            coolers_customers: {
                name: string;
                id: number;
                email: string | null;
                depot_id: number | null;
                phone_number: string | null;
                address: string | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                latitude: import("@prisma/client-runtime-utils").Decimal | null;
                longitude: import("@prisma/client-runtime-utils").Decimal | null;
                code: string;
                short_name: string | null;
                zones_id: number | null;
                customer_type_id: number | null;
                customer_channel_id: number | null;
                customer_category_id: number | null;
                type: string | null;
                gps_status: string | null;
                internal_code_one: string | null;
                internal_code_two: string | null;
                contact_person: string | null;
                city: string | null;
                state: string | null;
                zipcode: string | null;
                credit_limit: import("@prisma/client-runtime-utils").Decimal | null;
                outstanding_amount: import("@prisma/client-runtime-utils").Decimal | null;
                route_id: number | null;
                salesperson_id: number | null;
                nfc_tag_code: string | null;
                last_visit_date: Date | null;
                outlet_images: string | null;
                profile_picture: string | null;
            };
        } & {
            brand: string | null;
            model: string | null;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            status: string | null;
            technician_id: number | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            customer_id: number;
            code: string;
            asset_master_id: number | null;
            serial_number: string | null;
            capacity: number | null;
            install_date: Date | null;
            last_service_date: Date | null;
            next_service_due: Date | null;
            cooler_type_id: number | null;
            cooler_sub_type_id: number | null;
            energy_rating: string | null;
            warranty_expiry: Date | null;
            maintenance_contract: string | null;
            last_scanned_date: Date | null;
        })[]>;
        coolerInspections: (_: any, { filter, limit, offset }: any) => Promise<({
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            };
            coolers: {
                brand: string | null;
                model: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                technician_id: number | null;
                temperature: import("@prisma/client-runtime-utils").Decimal | null;
                customer_id: number;
                code: string;
                asset_master_id: number | null;
                serial_number: string | null;
                capacity: number | null;
                install_date: Date | null;
                last_service_date: Date | null;
                next_service_due: Date | null;
                cooler_type_id: number | null;
                cooler_sub_type_id: number | null;
                energy_rating: string | null;
                warranty_expiry: Date | null;
                maintenance_contract: string | null;
                last_scanned_date: Date | null;
            };
            visits: {
                customer_image: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                customer_id: number;
                zones_id: number | null;
                route_id: number | null;
                sales_person_id: number;
                visit_date: Date | null;
                visit_time: string | null;
                purpose: string | null;
                start_time: Date | null;
                end_time: Date | null;
                duration: number | null;
                cooler_image: string | null;
                self_image: string | null;
                start_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                start_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                check_in_time: Date | null;
                check_out_time: Date | null;
                orders_created: number | null;
                amount_collected: import("@prisma/client-runtime-utils").Decimal | null;
                visit_notes: string | null;
                customer_feedback: string | null;
                next_visit_date: Date | null;
            } | null;
        } & {
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            action_taken: string | null;
            cooler_id: number;
            visit_id: number | null;
            inspected_by: number;
            inspection_date: Date | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            is_working: string;
            issues: string | null;
            images: string | null;
            latitude: import("@prisma/client-runtime-utils").Decimal | null;
            longitude: import("@prisma/client-runtime-utils").Decimal | null;
            action_required: string;
            next_inspection_due: Date | null;
        })[]>;
        coolerInspection: (_: any, { id }: {
            id: number;
        }) => Promise<({
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            };
            coolers: {
                brand: string | null;
                model: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                technician_id: number | null;
                temperature: import("@prisma/client-runtime-utils").Decimal | null;
                customer_id: number;
                code: string;
                asset_master_id: number | null;
                serial_number: string | null;
                capacity: number | null;
                install_date: Date | null;
                last_service_date: Date | null;
                next_service_due: Date | null;
                cooler_type_id: number | null;
                cooler_sub_type_id: number | null;
                energy_rating: string | null;
                warranty_expiry: Date | null;
                maintenance_contract: string | null;
                last_scanned_date: Date | null;
            };
            visits: {
                customer_image: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                customer_id: number;
                zones_id: number | null;
                route_id: number | null;
                sales_person_id: number;
                visit_date: Date | null;
                visit_time: string | null;
                purpose: string | null;
                start_time: Date | null;
                end_time: Date | null;
                duration: number | null;
                cooler_image: string | null;
                self_image: string | null;
                start_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                start_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                check_in_time: Date | null;
                check_out_time: Date | null;
                orders_created: number | null;
                amount_collected: import("@prisma/client-runtime-utils").Decimal | null;
                visit_notes: string | null;
                customer_feedback: string | null;
                next_visit_date: Date | null;
            } | null;
        } & {
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            action_taken: string | null;
            cooler_id: number;
            visit_id: number | null;
            inspected_by: number;
            inspection_date: Date | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            is_working: string;
            issues: string | null;
            images: string | null;
            latitude: import("@prisma/client-runtime-utils").Decimal | null;
            longitude: import("@prisma/client-runtime-utils").Decimal | null;
            action_required: string;
            next_inspection_due: Date | null;
        }) | null>;
        coolerInspectionsByCooler: (_: any, { coolerId }: {
            coolerId: number;
        }) => Promise<({
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            };
            coolers: {
                brand: string | null;
                model: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                technician_id: number | null;
                temperature: import("@prisma/client-runtime-utils").Decimal | null;
                customer_id: number;
                code: string;
                asset_master_id: number | null;
                serial_number: string | null;
                capacity: number | null;
                install_date: Date | null;
                last_service_date: Date | null;
                next_service_due: Date | null;
                cooler_type_id: number | null;
                cooler_sub_type_id: number | null;
                energy_rating: string | null;
                warranty_expiry: Date | null;
                maintenance_contract: string | null;
                last_scanned_date: Date | null;
            };
            visits: {
                customer_image: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                customer_id: number;
                zones_id: number | null;
                route_id: number | null;
                sales_person_id: number;
                visit_date: Date | null;
                visit_time: string | null;
                purpose: string | null;
                start_time: Date | null;
                end_time: Date | null;
                duration: number | null;
                cooler_image: string | null;
                self_image: string | null;
                start_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                start_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                check_in_time: Date | null;
                check_out_time: Date | null;
                orders_created: number | null;
                amount_collected: import("@prisma/client-runtime-utils").Decimal | null;
                visit_notes: string | null;
                customer_feedback: string | null;
                next_visit_date: Date | null;
            } | null;
        } & {
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            action_taken: string | null;
            cooler_id: number;
            visit_id: number | null;
            inspected_by: number;
            inspection_date: Date | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            is_working: string;
            issues: string | null;
            images: string | null;
            latitude: import("@prisma/client-runtime-utils").Decimal | null;
            longitude: import("@prisma/client-runtime-utils").Decimal | null;
            action_required: string;
            next_inspection_due: Date | null;
        })[]>;
        coolerInspectionsByInspector: (_: any, { inspectedBy }: {
            inspectedBy: number;
        }) => Promise<({
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            };
            coolers: {
                brand: string | null;
                model: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                technician_id: number | null;
                temperature: import("@prisma/client-runtime-utils").Decimal | null;
                customer_id: number;
                code: string;
                asset_master_id: number | null;
                serial_number: string | null;
                capacity: number | null;
                install_date: Date | null;
                last_service_date: Date | null;
                next_service_due: Date | null;
                cooler_type_id: number | null;
                cooler_sub_type_id: number | null;
                energy_rating: string | null;
                warranty_expiry: Date | null;
                maintenance_contract: string | null;
                last_scanned_date: Date | null;
            };
            visits: {
                customer_image: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                customer_id: number;
                zones_id: number | null;
                route_id: number | null;
                sales_person_id: number;
                visit_date: Date | null;
                visit_time: string | null;
                purpose: string | null;
                start_time: Date | null;
                end_time: Date | null;
                duration: number | null;
                cooler_image: string | null;
                self_image: string | null;
                start_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                start_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                check_in_time: Date | null;
                check_out_time: Date | null;
                orders_created: number | null;
                amount_collected: import("@prisma/client-runtime-utils").Decimal | null;
                visit_notes: string | null;
                customer_feedback: string | null;
                next_visit_date: Date | null;
            } | null;
        } & {
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            action_taken: string | null;
            cooler_id: number;
            visit_id: number | null;
            inspected_by: number;
            inspection_date: Date | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            is_working: string;
            issues: string | null;
            images: string | null;
            latitude: import("@prisma/client-runtime-utils").Decimal | null;
            longitude: import("@prisma/client-runtime-utils").Decimal | null;
            action_required: string;
            next_inspection_due: Date | null;
        })[]>;
    };
    Mutation: {
        createAssetMaster: (_: any, { input }: any) => Promise<{
            asset_master_asset_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                asset_type_id: number;
                description: string | null;
            } | null;
            asset_master_asset_types: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                category: string | null;
                description: string | null;
            };
        } & {
            brand: string | null;
            name: string;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            code: string;
            serial_number: string;
            warranty_expiry: Date | null;
            asset_type_id: number;
            assigned_to: string | null;
            barcode: string | null;
            nfc_tag: string | null;
            purchase_date: Date | null;
            current_location: string | null;
            current_status: string | null;
            asset_sub_type_id: number | null;
        }>;
        updateAssetMaster: (_: any, { id, input }: any) => Promise<{
            asset_master_asset_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                asset_type_id: number;
                description: string | null;
            } | null;
            asset_master_asset_types: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                category: string | null;
                description: string | null;
            };
        } & {
            brand: string | null;
            name: string;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            code: string;
            serial_number: string;
            warranty_expiry: Date | null;
            asset_type_id: number;
            assigned_to: string | null;
            barcode: string | null;
            nfc_tag: string | null;
            purchase_date: Date | null;
            current_location: string | null;
            current_status: string | null;
            asset_sub_type_id: number | null;
        }>;
        deleteAssetMaster: (_: any, { id }: {
            id: number;
        }) => Promise<{
            asset_master_asset_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                asset_type_id: number;
                description: string | null;
            } | null;
            asset_master_asset_types: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                category: string | null;
                description: string | null;
            };
        } & {
            brand: string | null;
            name: string;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            code: string;
            serial_number: string;
            warranty_expiry: Date | null;
            asset_type_id: number;
            assigned_to: string | null;
            barcode: string | null;
            nfc_tag: string | null;
            purchase_date: Date | null;
            current_location: string | null;
            current_status: string | null;
            asset_sub_type_id: number | null;
        }>;
        createCooler: (_: any, { input }: any) => Promise<{
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            } | null;
            cooler_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                description: string | null;
            } | null;
            cooler_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                cooler_type_id: number;
                description: string | null;
            } | null;
            cooler_asset_master: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                serial_number: string;
                warranty_expiry: Date | null;
                asset_type_id: number;
                assigned_to: string | null;
                barcode: string | null;
                nfc_tag: string | null;
                purchase_date: Date | null;
                current_location: string | null;
                current_status: string | null;
                asset_sub_type_id: number | null;
            } | null;
            coolers_customers: {
                name: string;
                id: number;
                email: string | null;
                depot_id: number | null;
                phone_number: string | null;
                address: string | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                latitude: import("@prisma/client-runtime-utils").Decimal | null;
                longitude: import("@prisma/client-runtime-utils").Decimal | null;
                code: string;
                short_name: string | null;
                zones_id: number | null;
                customer_type_id: number | null;
                customer_channel_id: number | null;
                customer_category_id: number | null;
                type: string | null;
                gps_status: string | null;
                internal_code_one: string | null;
                internal_code_two: string | null;
                contact_person: string | null;
                city: string | null;
                state: string | null;
                zipcode: string | null;
                credit_limit: import("@prisma/client-runtime-utils").Decimal | null;
                outstanding_amount: import("@prisma/client-runtime-utils").Decimal | null;
                route_id: number | null;
                salesperson_id: number | null;
                nfc_tag_code: string | null;
                last_visit_date: Date | null;
                outlet_images: string | null;
                profile_picture: string | null;
            };
        } & {
            brand: string | null;
            model: string | null;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            status: string | null;
            technician_id: number | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            customer_id: number;
            code: string;
            asset_master_id: number | null;
            serial_number: string | null;
            capacity: number | null;
            install_date: Date | null;
            last_service_date: Date | null;
            next_service_due: Date | null;
            cooler_type_id: number | null;
            cooler_sub_type_id: number | null;
            energy_rating: string | null;
            warranty_expiry: Date | null;
            maintenance_contract: string | null;
            last_scanned_date: Date | null;
        }>;
        updateCooler: (_: any, { id, input }: any) => Promise<{
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            } | null;
            cooler_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                description: string | null;
            } | null;
            cooler_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                cooler_type_id: number;
                description: string | null;
            } | null;
            cooler_asset_master: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                serial_number: string;
                warranty_expiry: Date | null;
                asset_type_id: number;
                assigned_to: string | null;
                barcode: string | null;
                nfc_tag: string | null;
                purchase_date: Date | null;
                current_location: string | null;
                current_status: string | null;
                asset_sub_type_id: number | null;
            } | null;
            coolers_customers: {
                name: string;
                id: number;
                email: string | null;
                depot_id: number | null;
                phone_number: string | null;
                address: string | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                latitude: import("@prisma/client-runtime-utils").Decimal | null;
                longitude: import("@prisma/client-runtime-utils").Decimal | null;
                code: string;
                short_name: string | null;
                zones_id: number | null;
                customer_type_id: number | null;
                customer_channel_id: number | null;
                customer_category_id: number | null;
                type: string | null;
                gps_status: string | null;
                internal_code_one: string | null;
                internal_code_two: string | null;
                contact_person: string | null;
                city: string | null;
                state: string | null;
                zipcode: string | null;
                credit_limit: import("@prisma/client-runtime-utils").Decimal | null;
                outstanding_amount: import("@prisma/client-runtime-utils").Decimal | null;
                route_id: number | null;
                salesperson_id: number | null;
                nfc_tag_code: string | null;
                last_visit_date: Date | null;
                outlet_images: string | null;
                profile_picture: string | null;
            };
        } & {
            brand: string | null;
            model: string | null;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            status: string | null;
            technician_id: number | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            customer_id: number;
            code: string;
            asset_master_id: number | null;
            serial_number: string | null;
            capacity: number | null;
            install_date: Date | null;
            last_service_date: Date | null;
            next_service_due: Date | null;
            cooler_type_id: number | null;
            cooler_sub_type_id: number | null;
            energy_rating: string | null;
            warranty_expiry: Date | null;
            maintenance_contract: string | null;
            last_scanned_date: Date | null;
        }>;
        deleteCooler: (_: any, { id }: {
            id: number;
        }) => Promise<{
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            } | null;
            cooler_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                description: string | null;
            } | null;
            cooler_sub_types: {
                name: string;
                id: number;
                is_active: string;
                createdate: Date;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                cooler_type_id: number;
                description: string | null;
            } | null;
            cooler_asset_master: {
                brand: string | null;
                name: string;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                code: string;
                serial_number: string;
                warranty_expiry: Date | null;
                asset_type_id: number;
                assigned_to: string | null;
                barcode: string | null;
                nfc_tag: string | null;
                purchase_date: Date | null;
                current_location: string | null;
                current_status: string | null;
                asset_sub_type_id: number | null;
            } | null;
            coolers_customers: {
                name: string;
                id: number;
                email: string | null;
                depot_id: number | null;
                phone_number: string | null;
                address: string | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                latitude: import("@prisma/client-runtime-utils").Decimal | null;
                longitude: import("@prisma/client-runtime-utils").Decimal | null;
                code: string;
                short_name: string | null;
                zones_id: number | null;
                customer_type_id: number | null;
                customer_channel_id: number | null;
                customer_category_id: number | null;
                type: string | null;
                gps_status: string | null;
                internal_code_one: string | null;
                internal_code_two: string | null;
                contact_person: string | null;
                city: string | null;
                state: string | null;
                zipcode: string | null;
                credit_limit: import("@prisma/client-runtime-utils").Decimal | null;
                outstanding_amount: import("@prisma/client-runtime-utils").Decimal | null;
                route_id: number | null;
                salesperson_id: number | null;
                nfc_tag_code: string | null;
                last_visit_date: Date | null;
                outlet_images: string | null;
                profile_picture: string | null;
            };
        } & {
            brand: string | null;
            model: string | null;
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            status: string | null;
            technician_id: number | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            customer_id: number;
            code: string;
            asset_master_id: number | null;
            serial_number: string | null;
            capacity: number | null;
            install_date: Date | null;
            last_service_date: Date | null;
            next_service_due: Date | null;
            cooler_type_id: number | null;
            cooler_sub_type_id: number | null;
            energy_rating: string | null;
            warranty_expiry: Date | null;
            maintenance_contract: string | null;
            last_scanned_date: Date | null;
        }>;
        createCoolerInspection: (_: any, { input }: any) => Promise<{
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            };
            coolers: {
                brand: string | null;
                model: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                technician_id: number | null;
                temperature: import("@prisma/client-runtime-utils").Decimal | null;
                customer_id: number;
                code: string;
                asset_master_id: number | null;
                serial_number: string | null;
                capacity: number | null;
                install_date: Date | null;
                last_service_date: Date | null;
                next_service_due: Date | null;
                cooler_type_id: number | null;
                cooler_sub_type_id: number | null;
                energy_rating: string | null;
                warranty_expiry: Date | null;
                maintenance_contract: string | null;
                last_scanned_date: Date | null;
            };
            visits: {
                customer_image: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                customer_id: number;
                zones_id: number | null;
                route_id: number | null;
                sales_person_id: number;
                visit_date: Date | null;
                visit_time: string | null;
                purpose: string | null;
                start_time: Date | null;
                end_time: Date | null;
                duration: number | null;
                cooler_image: string | null;
                self_image: string | null;
                start_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                start_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                check_in_time: Date | null;
                check_out_time: Date | null;
                orders_created: number | null;
                amount_collected: import("@prisma/client-runtime-utils").Decimal | null;
                visit_notes: string | null;
                customer_feedback: string | null;
                next_visit_date: Date | null;
            } | null;
        } & {
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            action_taken: string | null;
            cooler_id: number;
            visit_id: number | null;
            inspected_by: number;
            inspection_date: Date | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            is_working: string;
            issues: string | null;
            images: string | null;
            latitude: import("@prisma/client-runtime-utils").Decimal | null;
            longitude: import("@prisma/client-runtime-utils").Decimal | null;
            action_required: string;
            next_inspection_due: Date | null;
        }>;
        updateCoolerInspection: (_: any, { id, input }: any) => Promise<{
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            };
            coolers: {
                brand: string | null;
                model: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                technician_id: number | null;
                temperature: import("@prisma/client-runtime-utils").Decimal | null;
                customer_id: number;
                code: string;
                asset_master_id: number | null;
                serial_number: string | null;
                capacity: number | null;
                install_date: Date | null;
                last_service_date: Date | null;
                next_service_due: Date | null;
                cooler_type_id: number | null;
                cooler_sub_type_id: number | null;
                energy_rating: string | null;
                warranty_expiry: Date | null;
                maintenance_contract: string | null;
                last_scanned_date: Date | null;
            };
            visits: {
                customer_image: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                customer_id: number;
                zones_id: number | null;
                route_id: number | null;
                sales_person_id: number;
                visit_date: Date | null;
                visit_time: string | null;
                purpose: string | null;
                start_time: Date | null;
                end_time: Date | null;
                duration: number | null;
                cooler_image: string | null;
                self_image: string | null;
                start_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                start_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                check_in_time: Date | null;
                check_out_time: Date | null;
                orders_created: number | null;
                amount_collected: import("@prisma/client-runtime-utils").Decimal | null;
                visit_notes: string | null;
                customer_feedback: string | null;
                next_visit_date: Date | null;
            } | null;
        } & {
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            action_taken: string | null;
            cooler_id: number;
            visit_id: number | null;
            inspected_by: number;
            inspection_date: Date | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            is_working: string;
            issues: string | null;
            images: string | null;
            latitude: import("@prisma/client-runtime-utils").Decimal | null;
            longitude: import("@prisma/client-runtime-utils").Decimal | null;
            action_required: string;
            next_inspection_due: Date | null;
        }>;
        deleteCoolerInspection: (_: any, { id }: {
            id: number;
        }) => Promise<{
            users: {
                name: string;
                id: number;
                email: string;
                role_id: number;
                password_hash: string;
                parent_id: number | null;
                depot_id: number | null;
                sap_code: string | null;
                zone_id: number | null;
                phone_number: string | null;
                address: string | null;
                employee_id: string;
                joining_date: Date | null;
                reporting_to: number | null;
                profile_image: string | null;
                last_login: Date | null;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                platform: string | null;
            };
            coolers: {
                brand: string | null;
                model: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                technician_id: number | null;
                temperature: import("@prisma/client-runtime-utils").Decimal | null;
                customer_id: number;
                code: string;
                asset_master_id: number | null;
                serial_number: string | null;
                capacity: number | null;
                install_date: Date | null;
                last_service_date: Date | null;
                next_service_due: Date | null;
                cooler_type_id: number | null;
                cooler_sub_type_id: number | null;
                energy_rating: string | null;
                warranty_expiry: Date | null;
                maintenance_contract: string | null;
                last_scanned_date: Date | null;
            };
            visits: {
                customer_image: string | null;
                id: number;
                is_active: string;
                createdate: Date | null;
                createdby: number;
                updatedate: Date | null;
                updatedby: number | null;
                log_inst: number | null;
                status: string | null;
                customer_id: number;
                zones_id: number | null;
                route_id: number | null;
                sales_person_id: number;
                visit_date: Date | null;
                visit_time: string | null;
                purpose: string | null;
                start_time: Date | null;
                end_time: Date | null;
                duration: number | null;
                cooler_image: string | null;
                self_image: string | null;
                start_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                start_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_latitude: import("@prisma/client-runtime-utils").Decimal | null;
                end_longitude: import("@prisma/client-runtime-utils").Decimal | null;
                check_in_time: Date | null;
                check_out_time: Date | null;
                orders_created: number | null;
                amount_collected: import("@prisma/client-runtime-utils").Decimal | null;
                visit_notes: string | null;
                customer_feedback: string | null;
                next_visit_date: Date | null;
            } | null;
        } & {
            id: number;
            is_active: string;
            createdate: Date | null;
            createdby: number;
            updatedate: Date | null;
            updatedby: number | null;
            log_inst: number | null;
            action_taken: string | null;
            cooler_id: number;
            visit_id: number | null;
            inspected_by: number;
            inspection_date: Date | null;
            temperature: import("@prisma/client-runtime-utils").Decimal | null;
            is_working: string;
            issues: string | null;
            images: string | null;
            latitude: import("@prisma/client-runtime-utils").Decimal | null;
            longitude: import("@prisma/client-runtime-utils").Decimal | null;
            action_required: string;
            next_inspection_due: Date | null;
        }>;
    };
};
//# sourceMappingURL=resolvers.d.ts.map